# Generated by Django 5.0.1 on 2024-01-13 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotion', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotionrecord',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='emotion_videos/'),
        ),
        migrations.AlterField(
            model_name='emotionrecord',
            name='emotion_level',
            field=models.CharField(choices=[('angry', 'Angry'), ('disgust', 'Disgust'), ('fear', 'Fear'), ('happy', 'Happy'), ('sad', 'Sad'), ('surprise', 'Surprise'), ('neutral', 'Neutral')], max_length=20),
        ),
        migrations.AlterField(
            model_name='emotionrecord',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='emotion_images/'),
        ),
    ]
