# Generated by Django 5.0.1 on 2024-01-02 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_customuser_confirmation_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='emotion_record',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='counselor',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='student',
        ),
        migrations.DeleteModel(
            name='EmotionRecord',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
